<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Delete' => 'Уничтожить',
    'Save' => 'Сохранить',
    'Search' => 'Искать',
    'Update' => 'Поменять',
    'View' => 'Смотреть',
    'About' => 'О проекте',
    'Don`t know password?' => 'Не знаете пароля?',
    'Fill out the form below to sign-in and manage Redis Database' => 'Заполни формочку и получи власть над своими редисками',
    'Login' => 'Авторизация',
    'Logout' => 'Уйти',
    'Main' => 'Главная и почти единственная',
    'To modify the username/password, please check out the code' => 'Логин/пароль спрятаны в модели',
];
